-- Git / VCS Integration - see the "inbound webhook, not scheduled polling" and "approvals via
-- webhook events, not a follow-up API call" ADRs: zero credentials, zero outbound calls. webhook
-- secret is generated by VantaCore itself (not user-supplied) and encrypted at rest, same as import
-- connection tokens (see CredentialEncryptor).
CREATE TABLE vcs_connections (
    id uuid NOT NULL,
    project_id uuid NOT NULL,
    provider character varying(20) NOT NULL,
    repo_url character varying(500) NOT NULL,
    encrypted_webhook_secret text NOT NULL,
    created_by_user_id uuid,
    created_at timestamp(6) with time zone NOT NULL
);

ALTER TABLE ONLY vcs_connections ADD CONSTRAINT vcs_connections_pkey PRIMARY KEY (id);
ALTER TABLE ONLY vcs_connections ADD CONSTRAINT fk_vcs_connections_project FOREIGN KEY (project_id) REFERENCES projects(id);

CREATE INDEX idx_vcs_connections_project ON vcs_connections (project_id);

-- One row per ticket (ticket_id is the PK, not a synthetic id) - branches/commits/pull_requests/
-- deployments are jsonb arrays mutated in place by webhook receivers under a row lock (see
-- JpaDevelopmentActivityRepositoryAdapter.update) rather than normalized child tables, since every
-- write here is "load, upsert one entry by its own key, save the whole thing back", the same
-- full-replace shape already used for ProjectEntity/TicketEntity.
CREATE TABLE development_activities (
    ticket_id uuid NOT NULL,
    branches jsonb NOT NULL DEFAULT '[]',
    commits jsonb NOT NULL DEFAULT '[]',
    pull_requests jsonb NOT NULL DEFAULT '[]',
    deployments jsonb NOT NULL DEFAULT '[]'
);

ALTER TABLE ONLY development_activities ADD CONSTRAINT development_activities_pkey PRIMARY KEY (ticket_id);
ALTER TABLE ONLY development_activities ADD CONSTRAINT fk_development_activities_ticket FOREIGN KEY (ticket_id) REFERENCES tickets(id);
