package vantaCore.application.vcs.domain;

import vantaCore.application.vcs.domain.vo.VcsConnectionId;
import vantaCore.application.vcs.domain.vo.VcsProvider;

import java.time.Instant;
import java.util.UUID;

/** Otherwise write-once - create or delete, no general update endpoint (mirrors FileAggregate/
 ImportConnectionAggregate) - regenerateSecret() is the one deliberate exception, covering the
 "lost the secret" recovery gap (same reasoning as WebhookSubscriptionAggregate's own
 regenerateSecret()). No credential field at all, deliberately - see the "inbound webhook, not
 scheduled polling" ADR on the Git / VCS Integration sub-project. webhookSecret is generated by
 VantaCore itself, never supplied by the caller. */
public class VcsConnectionAggregate {
    private final VcsConnectionId id;
    private final UUID projectId;
    private final VcsProvider provider;
    private final String repoUrl;
    private final String webhookSecret;
    private final UUID createdByUserId;
    private final Instant createdAt;

    private VcsConnectionAggregate(
        VcsConnectionId id,
        UUID projectId,
        VcsProvider provider,
        String repoUrl,
        String webhookSecret,
        UUID createdByUserId,
        Instant createdAt
    ) {
        this.id = id;
        this.projectId = projectId;
        this.provider = provider;
        this.repoUrl = repoUrl;
        this.webhookSecret = webhookSecret;
        this.createdByUserId = createdByUserId;
        this.createdAt = createdAt;
    }

    public static VcsConnectionAggregate newConnection(
        VcsConnectionId id,
        UUID projectId,
        VcsProvider provider,
        String repoUrl,
        String webhookSecret,
        UUID createdByUserId,
        Instant createdAt
    ) {
        return new VcsConnectionAggregate(id, projectId, provider, repoUrl, webhookSecret, createdByUserId, createdAt);
    }

    /** Invalidates the previous secret by replacing it outright - id/projectId/provider/repoUrl/
     createdByUserId/createdAt all carry over from the current instance. The caller (see
     RegenerateVcsConnectionSecretQueryHandler) is responsible for re-deriving the connection's
     webhookUrl afterwards, since Bitbucket's variant embeds the secret in the URL itself. */
    public VcsConnectionAggregate regenerateSecret(String newSecret) {
        return new VcsConnectionAggregate(this.id, this.projectId, this.provider, this.repoUrl, newSecret, this.createdByUserId, this.createdAt);
    }

    public VcsConnectionId getId() {
        return id;
    }

    public UUID getProjectId() {
        return projectId;
    }

    public VcsProvider getProvider() {
        return provider;
    }

    public String getRepoUrl() {
        return repoUrl;
    }

    public String getWebhookSecret() {
        return webhookSecret;
    }

    public UUID getCreatedByUserId() {
        return createdByUserId;
    }

    public Instant getCreatedAt() {
        return createdAt;
    }
}
